TERMUX_PKG_HOMEPAGE=https://github.com/PJK/libcbor
TERMUX_PKG_DESCRIPTION="CBOR protocol implementation for C"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_LICENSE_FILE="LICENSE.md"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.13.0
TERMUX_PKG_SRCURL=https://github.com/PJK/libcbor/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=95a7f0dd333fd1dce3e4f92691ca8be38227b27887599b21cd3c4f6d6a7abb10
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DWITH_TESTS=OFF
-DWITH_EXAMPLES=OFF
-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF
"
